[workspace]
resolver = "2"
members = [
    "crates/canokey-protocol",
    "crates/canokey-compat",
    "crates/canokey-admin",
    "crates/canokey-piv",
    "crates/canokey-key",
    "crates/canokey-openpgp",
    "crates/canokey-oath",
    "crates/canokey-ndef",
    "crates/canokey-ctap",
    "crates/canokey",
    "crates/canokey-c",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
authors = ["canokeys.org"]
license = "Apache-2.0"
homepage = "https://canokeys.org"
repository = "https://github.com/canokeys/libcanokey"

[workspace.dependencies]
zeroize = "1.8"
thiserror = "2"
canokey-protocol = { path = "crates/canokey-protocol", version = "0.1.0" }
canokey-compat = { path = "crates/canokey-compat", version = "0.1.0" }
canokey-admin = { path = "crates/canokey-admin", version = "0.1.0" }
canokey-oath = { path = "crates/canokey-oath", version = "0.1.0" }
canokey-ndef = { path = "crates/canokey-ndef", version = "0.1.0" }
canokey-ctap = { path = "crates/canokey-ctap", version = "0.1.0", default-features = false }
canokey-key = { path = "crates/canokey-key", version = "0.1.0" }
canokey-openpgp = { path = "crates/canokey-openpgp", version = "0.1.0" }
canokey-piv = { path = "crates/canokey-piv", version = "0.1.0" }
canokey = { path = "crates/canokey", version = "0.1.0" }
x509-info = "0.1.1"
