[package]
name = "canokey"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Transport-free CanoKey host protocol library"
readme = "README.md"

[dependencies]
canokey-protocol.workspace = true
canokey-compat.workspace = true
canokey-admin.workspace = true
canokey-piv.workspace = true
canokey-oath.workspace = true
canokey-openpgp.workspace = true
canokey-ndef.workspace = true
canokey-ctap.workspace = true

x509-info = { workspace = true, optional = true }

[features]
x509 = ["dep:x509-info"]
serde = ["x509", "x509-info/serde"]
clientpin = ["canokey-ctap/clientpin"]

[package.metadata.docs.rs]
all-features = true
