[package]
name = "canokey-admin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
description = "CanoKey Admin applet bootstrap command builders"
publish = false

[dependencies]
canokey-protocol.workspace = true
