use canokey_protocol::{Error, ErrorKind, Phase, SecretBytes};
/// OATH credential name: one through 64 opaque bytes, with no UTF-8 assumption.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Name(Vec<u8>);
impl Name {
    /// Copy a bounded name; invalid lengths return InvalidArgument.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, Error> {
        if !(1..=64).contains(&bytes.len()) {
            return Err(Error::new(ErrorKind::InvalidArgument));
        }
        Ok(Self(bytes.to_vec()))
    }
    /// Original credential name bytes.
    pub fn as_bytes(&self) -> &[u8] {
        &self.0
    }
}
/// HMAC algorithm used by a credential, independent of the SHA-1 access protocol.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Algorithm {
    /// HMAC-SHA-1, 20-byte full response.
    Sha1,
    /// HMAC-SHA-256, 32-byte full response.
    Sha256,
    /// HMAC-SHA-512, 64-byte full response.
    Sha512,
}
impl Algorithm {
    pub(crate) fn wire(self) -> u8 {
        match self {
            Self::Sha1 => 1,
            Self::Sha256 => 2,
            Self::Sha512 => 3,
        }
    }
    pub(crate) fn len(self) -> usize {
        match self {
            Self::Sha1 => 20,
            Self::Sha256 => 32,
            Self::Sha512 => 64,
        }
    }
}
/// Credential counter source. HOTP counter advancement belongs to the device.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Kind {
    /// Device-maintained moving counter.
    Hotp,
    /// Caller-supplied time-step challenge.
    Totp,
}
impl Kind {
    pub(crate) fn wire(self) -> u8 {
        match self {
            Self::Hotp => 0x10,
            Self::Totp => 0x20,
        }
    }
}
/// Owned credential insertion input. Secrets are redacted and wiped on drop.
#[derive(Debug)]
pub struct Credential {
    /// Unique credential name; PUT does not silently replace an existing name.
    pub name: Name,
    /// Counter-based or time-based credential.
    pub kind: Kind,
    /// HMAC algorithm.
    pub algorithm: Algorithm,
    /// Decimal digit count, four through eight.
    pub digits: u8,
    /// One through 64 secret bytes. Longer HMAC keys must be normalized by callers.
    pub secret: SecretBytes,
    /// Require physical presence for individual calculation.
    pub require_touch: bool,
    /// Require increasing time challenges; allowed only for TOTP here.
    pub increasing: bool,
    /// Initial 32-bit HOTP counter; must be zero for TOTP. Pinned firmware
    /// increments this counter before calculation, so the first use consumes N+1.
    pub initial_counter: u32,
}
/// Owned 16-byte OATH access key; not a reusable authorization token.
#[derive(Debug)]
pub struct AccessKey(pub(crate) SecretBytes);
impl AccessKey {
    /// Copy exactly sixteen bytes; other lengths return InvalidArgument.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, Error> {
        if bytes.len() != 16 {
            return Err(Error::new(ErrorKind::InvalidArgument));
        }
        Ok(Self(SecretBytes::new(bytes.to_vec())))
    }
    /// Derive a key using the OATH password convention: PBKDF2-HMAC-SHA1,
    /// 1000 iterations, the SELECT eight-byte handle as salt, sixteen output bytes.
    /// This implements protocol compatibility, not a modern password-storage policy.
    /// Input is owned and wiped on return; callers own other password copies.
    pub fn from_password(password: SecretBytes, handle: [u8; 8]) -> Self {
        let mut output = zeroize::Zeroizing::new([0; 16]);
        pbkdf2::pbkdf2_hmac::<sha1::Sha1>(password.as_bytes(), &handle, 1000, output.as_mut());
        Self(SecretBytes::new(output.to_vec()))
    }
}
/// Explicit mutual access validation. Randomness is generated by the caller.
#[derive(Debug)]
pub struct Access {
    /// Key corresponding to the selected device's access-code configuration.
    pub key: AccessKey,
    /// Fresh eight-byte CSPRNG challenge; deterministic values are for tests only.
    pub challenge: [u8; 8],
}
/// SELECT observations; unknown fields remain in raw bytes and are not authorization.
#[derive(Debug)]
pub struct Selection {
    /// Applet version bytes, independent of actual firmware version.
    pub version: [u8; 3],
    /// Eight-byte device handle used as the password-derivation salt.
    pub handle: [u8; 8],
    /// Fresh card authentication challenge if an access code is installed.
    pub challenge: Option<[u8; 8]>,
    /// Access authentication algorithm observation (currently 1 for SHA-1).
    pub algorithm: Option<u8>,
    /// Complete original SELECT bytes; bounded by operation response budgets.
    pub raw: SecretBytes,
}
/// Calculation representation requested explicitly; never changed after a failure.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Format {
    /// Four-byte dynamic truncation, preceded on wire by the decimal digit count.
    Truncated,
    /// Complete HMAC bytes, preceded on wire by the decimal digit count.
    Full,
}
/// Keyboard-emulation touch slot for the default HOTP credential.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DefaultSlot {
    /// Short touch, wire value 0x01 in the two-slot dialect.
    Short,
    /// Long touch, wire value 0x02 in the two-slot dialect.
    Long,
}
impl DefaultSlot {
    pub(crate) fn wire(self) -> u8 {
        match self {
            Self::Short => 1,
            Self::Long => 2,
        }
    }
}
/// Owned OATH operation request.
#[derive(Debug)]
pub enum Request {
    /// SELECT observations only. Does not perform validation even if a code exists.
    Select,
    /// Explicitly validate access, requiring a supplied key and a card challenge.
    Validate,
    /// List names and algorithm/type octets without calculating codes.
    List,
    /// Insert a credential; duplicate-name status propagates.
    Put(Credential),
    /// Delete one credential.
    Delete(Name),
    /// Rename one credential without changing its key or counter.
    Rename {
        /// Existing name.
        old: Name,
        /// New name. Before 2.0, firmware does not reject an existing destination.
        new: Name,
    },
    /// Calculate one credential. Name/type/algorithm come from caller records.
    Calculate {
        /// Credential name.
        name: Name,
        /// Expected counter kind; no challenge for HOTP, eight bytes for TOTP.
        kind: Kind,
        /// Expected HMAC algorithm, used to validate full-response length.
        algorithm: Algorithm,
        /// Caller-derived TOTP time step as an eight-byte big-endian integer.
        challenge: Option<[u8; 8]>,
        /// Full HMAC or dynamic truncation.
        format: Format,
    },
    /// Calculate eligible TOTP entries. HOTP/touch entries return markers;
    /// increasing TOTP entries may persist state even if a later page fails.
    CalculateAll {
        /// Caller-derived time step, big-endian; library never reads a clock.
        challenge: [u8; 8],
        /// Full HMAC or dynamic truncation.
        format: Format,
    },
    /// Set/replace access code after any explicit current-key validation.
    SetCode {
        /// New 16-byte key.
        key: AccessKey,
        /// Fresh caller-supplied challenge used in the set-code proof.
        challenge: [u8; 8],
    },
    /// Remove access code, validating the supplied current key when protected.
    ClearCode,
    /// Mark an existing HOTP credential as the default emitted on touch through
    /// keyboard emulation; only HOTP credentials are eligible. This mutates the
    /// on-card PASS configuration; deleting the credential clears the slot
    /// firmware-side. Firmware before 3.0.0 has one slot and no enter flag, so
    /// `slot` must be Short and `append_enter` must be false there, or
    /// construction fails with InvalidArgument before any I/O.
    SetDefault {
        /// Touch slot; Long requires firmware 3.0.0 or newer.
        slot: DefaultSlot,
        /// Append an Enter keystroke after the emitted code; requires firmware
        /// 3.0.0 or newer.
        append_enter: bool,
        /// Existing credential name.
        name: Name,
    },
}
/// Listed credential with raw algorithm/type octet, preserving unknown values.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Entry {
    /// Original bounded name bytes.
    pub name: Name,
    /// High nibble type (1 HOTP, 2 TOTP); low nibble algorithm (1/2/3).
    pub algorithm_type: u8,
    /// Decimal digits observed by legacy LIST; modern LIST does not report them.
    pub digits: Option<u8>,
}
/// Calculation payload or explicit non-calculation marker. Code bytes are secret.
#[derive(Debug)]
pub enum Code {
    /// Four-byte dynamic truncation in big-endian order; highest bit must be zero.
    Truncated(SecretBytes),
    /// Full HMAC bytes; no host-side truncation is applied implicitly.
    Full(SecretBytes),
    /// HOTP was not calculated by CalculateAll.
    Hotp,
    /// Individual physical-presence calculation is required.
    TouchRequired,
}
/// One code result, optionally named when returned by CalculateAll.
#[derive(Debug)]
pub struct Calculation {
    /// Present for CalculateAll, absent for an individual calculation.
    pub name: Option<Name>,
    /// Observed four through eight decimal digits.
    pub digits: u8,
    /// Owned code bytes or explicit reason for no calculation.
    pub code: Code,
}
impl Calculation {
    /// Format an explicitly truncated code as zero-padded ASCII decimal bytes.
    /// Full-HMAC/marker results return None. The owned result is wiped on drop.
    pub fn decimal(&self) -> Option<SecretBytes> {
        let Code::Truncated(bytes) = &self.code else {
            return None;
        };
        let mut number = u32::from_be_bytes(bytes.as_bytes().try_into().ok()?);
        if !(4..=8).contains(&self.digits) {
            return None;
        }
        let mut output = vec![b'0'; self.digits as usize];
        for digit in output.iter_mut().rev() {
            *digit += (number % 10) as u8;
            number /= 10;
        }
        Some(SecretBytes::new(output))
    }
}
/// Completed owned OATH result; writes invalidate application credential caches.
#[derive(Debug)]
pub enum Outcome {
    /// SELECT data; not a persistent authenticated session.
    Selection(Selection),
    /// Legacy SELECT returned no applet version, salt or challenge. The optional
    /// four-byte Admin serial is copied from the profile, never synthesized as salt.
    LegacySelection {
        /// Independently observed Admin serial, when available.
        serial: Option<[u8; 4]>,
    },
    /// Credential list, in card order.
    Entries(Vec<Entry>),
    /// Individual or all-credential calculations, in card order.
    Calculations(Vec<Calculation>),
    /// Successful validation or empty mutation acknowledgment.
    Unit,
}
pub(crate) fn invalid() -> Error {
    Error::new(ErrorKind::InvalidResponse).at(Phase::Parsing)
}
