#include "canokey.h"
#include <assert.h>
#include <string.h>
static void feed(cnk_operation_t *op,const uint8_t *data,size_t n,uint32_t *step) {
    cnk_error_v1 err={0};err.struct_size=sizeof(err);
    assert(cnk_operation_advance(op,data,n,step,&err)==CNK_OK);
}
int main(void) {
    cnk_operation_t *op=NULL;
    cnk_profile_t *profile=NULL;
    cnk_error_v1 err={0};err.struct_size=sizeof(err);
    uint32_t step=0;
    const uint8_t ok[]={0x90,0};
    assert(cnk_abi_version()==1);
    assert(cnk_probe_device_new(CNK_PROBE_PIV,NULL,&op,&err)==CNK_OK);
    assert(cnk_operation_start(op,&step,&err)==CNK_OK);
    size_t n=0;assert(cnk_operation_command(op,NULL,&n)==CNK_OK&&n==11);
    uint8_t tiny[2]={0xaa,0xbb};n=sizeof(tiny);
    assert(cnk_operation_command(op,tiny,&n)==CNK_BUFFER_TOO_SMALL&&n==11);
    assert(tiny[0]==0xaa&&tiny[1]==0xbb);
    feed(op,ok,sizeof(ok),&step);
    const uint8_t fw[]={'9','.','0','.','0',0x90,0};feed(op,fw,sizeof(fw),&step);
    const uint8_t model[]={'C','K',0x90,0};feed(op,model,sizeof(model),&step);
    const uint8_t serial[]={1,2,3,4,0x90,0};feed(op,serial,sizeof(serial),&step);
    feed(op,ok,sizeof(ok),&step);
    const uint8_t piv[]={5,7,0,0x90,0};feed(op,piv,sizeof(piv),&step);
    assert(step==CNK_STEP_DONE);
    assert(cnk_operation_take_profile(op,&profile)==CNK_OK);
    uint32_t firmware_version[3], numeric_serial = 0;
    assert(cnk_profile_firmware_version(profile,firmware_version)==CNK_OK && firmware_version[0]==9);
    assert(cnk_profile_serial_u32(profile,&numeric_serial)==CNK_OK && numeric_serial==0x01020304);
    uint8_t model_copy[2];size_t model_len=sizeof(model_copy);
    assert(cnk_profile_model_copy(profile,model_copy,&model_len)==CNK_OK && model_len==2 && !memcmp(model_copy,"CK",2));
    cnk_error_v1 admission={0};admission.struct_size=sizeof(admission);
    assert(cnk_profile_piv_require_algorithm(profile,CNK_ALGORITHM_RSA2048,&admission)==CNK_PROTOCOL_ERROR);
    assert(admission.kind==CNK_ERROR_CAPABILITY_UNKNOWN && admission.presence_flags==0);
    cnk_profile_t *again=profile;
    assert(cnk_operation_take_profile(op,&again)==CNK_INVALID_STATE&&again==NULL);
    cnk_operation_free(op);op=NULL;
    uint8_t pin[]={'1','2','3','4','5','6'};
    assert(cnk_piv_verify_pin_new(profile,pin,sizeof(pin),NULL,&op,&err)==CNK_OK);
    cnk_operation_t *status_op=NULL,*object_op=NULL;
    assert(cnk_piv_get_pin_status_new(profile,NULL,&status_op,&err)==CNK_OK);
    const uint8_t tag[]={0x7e};
    assert(cnk_piv_read_object_new(profile,tag,sizeof(tag),NULL,&object_op,&err)==CNK_OK);
    cnk_operation_t *cert_op=NULL;
    assert(cnk_piv_read_certificate_new(profile,0x9b,NULL,&cert_op,&err)==CNK_INVALID_ARGUMENT&&cert_op==NULL);
    assert(cnk_piv_read_certificate_new(profile,0x9a,NULL,&cert_op,&err)==CNK_OK);
    cnk_profile_free(profile);profile=NULL;memset(pin,0,sizeof(pin));
    n=0;assert(cnk_operation_result_copy_bytes(cert_op,NULL,&n)==CNK_INVALID_STATE);
    assert(cnk_operation_start(cert_op,&step,&err)==CNK_OK);
    feed(cert_op,ok,sizeof(ok),&step);
    const uint8_t cert[]={0x53,9,0x70,2,0x30,0,0x71,1,0,0xfe,0,0x90,0};
    feed(cert_op,cert,sizeof(cert),&step);
    uint32_t cert_kind=0;
    assert(cnk_operation_result_kind(cert_op,&cert_kind)==CNK_OK&&cert_kind==CNK_RESULT_CERTIFICATE);
    assert(cnk_operation_result_copy_bytes(cert_op,NULL,&n)==CNK_OK&&n==2);
    n=1;tiny[0]=0xaa;
    assert(cnk_operation_result_copy_bytes(cert_op,tiny,&n)==CNK_BUFFER_TOO_SMALL&&tiny[0]==0xaa&&n==2);
    assert(cnk_operation_result_copy_bytes(cert_op,tiny,&n)==CNK_OK);
    cnk_operation_free(cert_op);
    assert(tiny[0]==0x30&&tiny[1]==0);
    assert(cnk_operation_start(op,&step,&err)==CNK_OK);feed(op,ok,sizeof(ok),&step);
    uint8_t command[32];n=sizeof(command);assert(cnk_operation_command(op,command,&n)==CNK_OK);
    assert(n==13&&memcmp(command+5,"123456",6)==0);
    const uint8_t wrong[]={0x63,0xc2};
    assert(cnk_operation_advance(op,wrong,sizeof(wrong),&step,&err)==CNK_PROTOCOL_ERROR);
    assert(step==0&&err.kind==CNK_ERROR_AUTHENTICATION_FAILED&&err.retries_remaining==2&&err.status_word==0x63c2);
    uint32_t state=0;
    assert(cnk_operation_state(op,&state)==CNK_OK&&state==CNK_STATE_FAILED);
    assert(cnk_operation_start(op,&step,&err)==CNK_INVALID_STATE);
    assert(cnk_operation_error(op,&err)==CNK_OK&&err.kind==CNK_ERROR_AUTHENTICATION_FAILED);
    cnk_operation_free(op);op=NULL;
    assert(cnk_operation_start(status_op,&step,&err)==CNK_OK);
    feed(status_op,ok,sizeof(ok),&step);feed(status_op,ok,sizeof(ok),&step);
    cnk_pin_status_v1 ps={0};ps.struct_size=sizeof(ps);
    assert(cnk_operation_pin_status(status_op,&ps)==CNK_OK);
    assert(ps.presence_flags==CNK_PIN_HAS_VERIFIED&&ps.verified==1);
    n=0;assert(cnk_operation_result_copy_bytes(status_op,NULL,&n)==CNK_RESULT_TYPE_MISMATCH);
    cnk_operation_free(status_op);
    cnk_operation_t *selected_status=NULL;
    assert(cnk_piv_get_pin_status_selected_new(NULL,&selected_status,&err)==CNK_OK);
    assert(cnk_operation_start(selected_status,&step,&err)==CNK_OK);
    n=0;assert(cnk_operation_command(selected_status,NULL,&n)==CNK_OK&&n==5);
    uint8_t verify[5];n=sizeof(verify);
    assert(cnk_operation_command(selected_status,verify,&n)==CNK_OK);
    assert(verify[1]==0x20&&verify[3]==0x80);
    const uint8_t retries[]={0x63,0xc2};feed(selected_status,retries,sizeof(retries),&step);
    cnk_pin_status_v1 ps2={0};ps2.struct_size=sizeof(ps2);
    assert(cnk_operation_pin_status(selected_status,&ps2)==CNK_OK);
    assert(ps2.presence_flags==(CNK_PIN_HAS_VERIFIED|CNK_PIN_HAS_REMAINING));
    assert(ps2.verified==0&&ps2.remaining==2&&ps2.blocked==0);
    cnk_operation_free(selected_status);
    assert(cnk_operation_start(object_op,&step,&err)==CNK_OK);feed(object_op,ok,sizeof(ok),&step);
    const uint8_t object[]={0x7e,3,1,2,3,0x90,0};feed(object_op,object,sizeof(object),&step);
    assert(cnk_operation_result_kind(object_op,&state)==CNK_OK&&state==CNK_RESULT_OBJECT);
    n=0;assert(cnk_operation_result_copy_bytes(object_op,NULL,&n)==CNK_OK&&n==3);
    n=2;tiny[0]=0xaa;tiny[1]=0xbb;
    assert(cnk_operation_result_copy_bytes(object_op,tiny,&n)==CNK_BUFFER_TOO_SMALL);
    assert(tiny[0]==0xaa&&tiny[1]==0xbb);
    uint8_t result[3];n=sizeof(result);
    assert(cnk_operation_result_copy_bytes(object_op,result,&n)==CNK_OK&&n==3);
    cnk_operation_free(object_op);assert(result[0]==1&&result[2]==3);
    cnk_operation_options_v1 invalid={0};invalid.struct_size=sizeof(invalid);
    assert(cnk_probe_device_new(CNK_PROBE_MINIMAL,&invalid,&op,&err)==CNK_INVALID_ARGUMENT&&op==NULL);
    assert(cnk_probe_device_new(CNK_PROBE_MINIMAL,NULL,&op,&err)==CNK_OK);
    assert(cnk_operation_cancel(op)==CNK_OK&&cnk_operation_cancel(op)==CNK_OK);
    assert(cnk_operation_state(op,&state)==CNK_OK&&state==CNK_STATE_CANCELLED);
    cnk_operation_free(op);cnk_operation_free(NULL);cnk_profile_free(NULL);
    cnk_operation_t *observed=NULL;
    const uint8_t pre[]={9,8,7,6};
    assert(cnk_probe_device_with_serial_new(CNK_PROBE_MINIMAL,pre,3,NULL,&observed,&err)==CNK_INVALID_ARGUMENT&&observed==NULL);
    assert(cnk_probe_device_with_serial_new(CNK_PROBE_MINIMAL,pre,4,NULL,&observed,&err)==CNK_OK);
    assert(cnk_operation_start(observed,&step,&err)==CNK_OK);
    feed(observed,ok,sizeof(ok),&step);
    feed(observed,fw,sizeof(fw),&step);
    feed(observed,model,sizeof(model),&step);
    assert(step==CNK_STEP_DONE);
    cnk_profile_t *observed_profile=NULL;
    assert(cnk_operation_take_profile(observed,&observed_profile)==CNK_OK);
    uint32_t observed_serial=0;
    assert(cnk_profile_serial_u32(observed_profile,&observed_serial)==CNK_OK&&observed_serial==0x09080706);
    cnk_profile_free(observed_profile);
    cnk_operation_free(observed);
    return 0;
}
